---

- name: Create Patch directory
  file:
    path: "{{ patch_directory }}"
    state: directory
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  run_once: true

- name: Unzip PSU
  unarchive:
    src: "{{ oracle_stage_install }}/{{ quarterly_patches[patch_type][oracle_version][patch_name][oracle_install_type].filename }}"
    dest: "{{ patch_directory}}/"
    copy: no
    creates: "{{ patch_directory }}/{{ quarterly_patches[patch_type][oracle_version][patch_name][oracle_install_type].patchid }}/README.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  run_once: true
  when: "'{{ patch_type }}' == 'psu' and not ansible_check_mode"

- name: Unzip DBBP
  unarchive:
    src: "{{ oracle_stage_install }}/{{ quarterly_patches[patch_type][oracle_version][patch_name].filename }}"
    dest: "{{ patch_directory}}/"
    copy: no
    creates: "{{ patch_directory }}/{{ quarterly_patches[patch_type][oracle_version][patch_name].patchid }}/README.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  run_once: true
  when: "'{{ patch_type }}' == 'dbbp' and not ansible_check_mode"

- name: Unzip oneoff patches
  unarchive:
    src: "{{ oracle_stage_install }}/{{ item.filename }}"
    dest: "{{ patch_directory }}/"
    copy: no
    creates: "{{ patch_directory }}/{{ item.patchid }}/README.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  with_items: "{{ oneoff_patches[ quarterly_patches[patch_type][oracle_version][patch_name].patchversion ]|default([]) }}"
  when: oneoff_patches[ quarterly_patches[patch_type][oracle_version][patch_name].patchversion ] is defined and not ansible_check_mode
  run_once: true
