---

- name: Rollback PSU Specific One-off Patches
  shell: "{{ oracle_home }}/OPatch/opatch rollback -silent -local -id {{ item.patchid }}"
  sudo: yes
  sudo_user: "{{ oracle_user }}"
  with_items: oneoff_patches[ psu[oracle_version][psu_name].patchversion ]|default([])
  when: oneoff_patches[ psu[oracle_version][psu_name].patchversion ] is defined
  register: oneoff_rollback
  ignore_errors: true

- debug: var=oneoff_rollback.results
