---
  #role: psu-apply
  #file: main.yml

- debug: var=patch_type

- name: Run pre-check tasks
  include: pre_checks.yml
  tags: pre_checks

- name: Stop EM Agent
  shell: "{{ agent_home }}/bin/emctl stop agent"
  become_user: "{{ oracle_user }}"
  when: agent_home is defined and shutdown_listener
  tags: stop_agent

- name: Rollback Quarterly Patch
  include: "rollback_{{ oracle_install_type }}.yml"
  become_user: "{{ oracle_user }}"
  tags: rollback

- name: Start EM Agent
  shell: "{{ agent_home }}/bin/emctl start agent"
  become: yes
  become_user: "{{ oracle_user }}"
  when: agent_home is defined and shutdown_listener
  tags: start_agent

- name: Opatch lsinventory
  shell: "{{ oracle_home }}/OPatch/opatch lsinventory -oh {{ oracle_home }}"
  become_user: "{{ oracle_user }}"
  with_items:
    - "{{ oracle_home }}"
    - "{{ grid_home|default(None) }}"
  when: item is defined
  register: lsinv_post

- debug: var=lsinv_post.results
