---
- debug: msg="ru_si_asm.yml - Patch Single Instance ASM (Oracle Restart)"



# - name: SI (ASM) | Opatch lsinventory
#   shell: "{{ item }}/OPatch/opatch lsinventory -oh {{ item }}"
#   become_user: "{{ oracle_user }}"
#   with_items:
#     - "{{ oracle_home }}"
#     - "{{ gi_home|default(omit) }}"
#   register: lsinv_pre

# - name: SI (ASM) | patch the GI home and all Oracle RAC database homes of the same version
#   shell: "{{ gi_home }}/OPatch/opatchauto apply {{ patch_directory }}/{{ quarterly_patches[patch_type][oracle_version][patch_name].patchid }}"
#   register: gi_opatchauto
#   when:
#     - oracle_version == gi_version
#
# - debug: var=gi_opatchauto

- name: SI (ASM) | Patch GI Home
  shell: "{{ gi_home }}/OPatch/opatchauto apply {{ patch_directory }}/{{ quarterly_patches[patch_type][oracle_version][patch_name].patchid }} -oh {{ gi_home }}"
  register: gi_opatchauto
  when:
    - oracle_version == gi_version

- debug: var=gi_opatchauto

- name: SI (ASM) | Patch Oracle Home
  shell: "{{ gi_home }}/OPatch/opatchauto apply {{ patch_directory }}/{{ quarterly_patches[patch_type][oracle_version][patch_name].patchid }} -oh {{ oracle_home }}"
  register: ora_opatchauto

- debug: var=ora_opatchauto
