---

- name: 11.2 - Load Modified SQL Files into the Database
  shell: export ORACLE_SID={{ item }}{{ host_num |default('') }}; echo exit | {{ oracle_home }}/bin/sqlplus -S / as sysdba @catbundle.sql psu apply
  sudo: yes
  sudo_user: "{{ oracle_user }}"
  register: catbundle
  environment: env
  with_items: dblist.stdout_lines
  args:
    chdir: "{{ oracle_home }}/rdbms/admin"
  run_once: true
  when: oracle_version == '11.2.0.4'
  tags: catbundle

- name: 12.1 - Load Modified SQL Files into the Database
  shell: "export ORACLE_SID={{ item }}; ./datapatch -verbose"
  sudo: yes
  sudo_user: "{{ oracle_user }}"
  register: datapatch
  environment: env
  with_items: dblist.stdout_lines
  args:
    chdir: "{{ oracle_home }}/OPatch"
  run_once: true
  failed_when: datapatch.rc == 1
  when: oracle_version == '12.1.0.2'
  ignore_errors: true
  tags: catbundle
