---

- name: 11.2 - Load Modified SQL Files into the Database
  shell: export ORACLE_SID={{ item }}{{ host_num |default('') }}; echo exit | sqlplus -S / as sysdba @catbundle.sql psu apply
  become_user: "{{ oracle_user }}"
  register: catbundle
  environment: "{{ env }}"
  with_items: "{{ dblist.stdout_lines }}"
  args:
    chdir: "{{ oracle_home }}/rdbms/admin"
  run_once: true
  when: "{{ oracle_version | version_compare('12.1', '<') }} and not ansible_check_mode"
  tags: catbundle

- name: 12.1 - Load Modified SQL Files into the Database
  shell: "export ORACLE_SID={{ item }}{{ host_num |default('') }}; ./datapatch -verbose"
  become_user: "{{ oracle_user }}"
  register: datapatch
  environment: "{{ env }}"
  with_items: "{{ dblist.stdout_lines }}"
  args:
    chdir: "{{ oracle_home }}/OPatch"
  run_once: true
  failed_when: datapatch.rc == 1
  when: "{{ oracle_version | version_compare('12.1', '>=') }} and not ansible_check_mode"
  ignore_errors: true
  tags: catbundle

# - name: Verify scripts directory exists
#   file:
#     path: /u01/oracle/scripts
#     state: directory
#     owner: oracle
#     group: oinstall
#     mode: 0755
#
# - name: Copy check_patches.sql
#   copy:
#     src: check_patches.sql
#     dest: /u01/oracle/scripts/check_patches.sql
#     owner: oracle
#     group: oinstall
#
# - name: Run check_patches.sql
#   shell: export ORACLE_SID={{ item }}{{ host_num |default('') }}; echo exit | sqlplus -S / as sysdba @check_patches.sql
#   environment: "{{ env }}"
#   with_items: "{{ dblist.stdout_lines }}"
#   args:
#     chdir: /u01/oracle/scripts
#   become_user: "{{ oracle_user }}"
#   register: sqlplus_result
#   failed_when: "'ERROR' in sqlplus_result.stdout or sqlplus_result.rc != 0"
#   run_once: true
#
# - debug: var=sqlplus_result.stdout_lines
