---
- debug: msg="dbbp_si_asm.12.1.0.2.yml - Patch 12.1.0.2 Single Instance ASM (Oracle Restart)"

- name: SI (ASM) | Patch 12.1 Database Home
  shell: "{{ oracle_home }}/OPatch/opatchauto apply {{ patch_directory }}/{{ patch_id }} -oh {{ oracle_home }}"
  register: dbbp_opatchauto

- debug: var=dbbp_opatchauto.stdout_lines

- name: srvctl stop home
  shell: "{{ oracle_home }}/bin/srvctl stop home -o {{ oracle_home }} -s {{ patch_directory }}/12c_srvctl.state -f"
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"

- name: Template patch list
  template:
    src: patch_list.j2
    dest: "{{ patch_directory }}/patch_list.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: patch_level[oracle_version].oneoff_patches is defined

- name: Opatch prereq check for oneoff patches
  shell: opatch prereq CheckConflictAgainstOHWithDetail -phBaseFile {{ patch_directory }}/patch_list.txt
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"
  register: oneoff_conflicts_psu
  when: patch_level[oracle_version].oneoff_patches is defined

- debug: var=oneoff_conflicts_psu.stdout_lines
  when: patch_level[oracle_version].oneoff_patches is defined

- name: Apply one-off patches
  shell: opatch napply -silent -phBaseFile {{ patch_directory }}/patch_list.txt
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"
  register: oneoff_apply_psu
  when: patch_level[oracle_version].oneoff_patches is defined

- debug: var=oneoff_apply_psu.stdout_lines
  when: patch_level[oracle_version].oneoff_patches is defined

- name: srvctl start home
  shell: "{{ oracle_home }}/bin/srvctl start home -o {{ oracle_home }} -s {{ patch_directory }}/12c_srvctl.state"
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"

- name: remove state file
  file:
    path: "{{ patch_directory }}/12c_srvctl.state"
    state: absent
