---

- name: Run srvctl start standalone home
  shell: $ORACLE_HOME/bin/srvctl start home -oraclehome $ORACLE_HOME -statefile {{ patch_directory | quote }}/19c_srvctl.state
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"
  ignore_errors: true
  when: (patch_level[oracle_version].oneoff_patches is defined and 
        (is_rac is not defined or not is_rac))


- name: Run srvctl start cluster home
  shell: $ORACLE_HOME/bin/srvctl start home -oraclehome $ORACLE_HOME -node $(hostname --short) -statefile {{ patch_directory | quote }}/19c_srvctl.state
  environment: "{{ env }}"
  become_user: "{{ oracle_user }}"
  ignore_errors: true
  when: (patch_level[oracle_version].oneoff_patches is defined and 
        (is_rac is defined and is_rac))
