---

- block:
  - name: Get active db instance list
    include_tasks: get_dbinstance_list.yml

  - name: Unset OJVM event
    shell: |
      ORACLE_SID="{{ item | quote }}"; export ORACLE_SID
      $ORACLE_HOME/bin/sqlplus /nolog <<-EOF
      connect / as sysdba
      alter system set events '29579 trace name context off';
      exit;
      EOF
    become_user: "{{ oracle_user }}"
    register: unset_ojvm_event_output
    environment: "{{ env }}"
    with_items: "{{ dblist.stdout_lines }}"
    ignore_errors: true

  run_once: true
  when: patch_level[oracle_version].oneoff_patches is defined
